apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-catalog-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-catalog-service
  template:
    metadata:
      labels:
        app: bookstore-catalog-service
    spec:
      containers:
      - name: catalog
        image: datfan06/bookstore-catalog-service:latest
        ports:
        - containerPort: 6001
        env:
        - name: SERVER_PORT
          value: "6001"
        - name: ZIPKIN_HOST
          value: "bookstore-zipkin:9411"
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-catalog-service
  namespace: bookstore
spec:
  type: NodePort
  ports:
    - port: 6001
      targetPort: 6001
      nodePort: 30006
  selector:
    app: bookstore-catalog-service 