apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bookstore
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093

    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # Added to get services from Eureka-Consul-Adapter
      - job_name: 'bookstore-consul-discovery'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        consul_sd_configs:
          - server: 'bookstore-consul-discovery:8500' # Host Ip where Consul is running.
        relabel_configs:
          - source_labels: ['__meta_consul_tags']
            action: keep
            # Example: keep only services with the 'prometheus' tag
            # regex: (.+prometheus.+) 
          - source_labels: ['__meta_consul_service']
            target_label: job
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-prometheus
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-prometheus
  template:
    metadata:
      labels:
        app: bookstore-prometheus
    spec:
      containers:
      - name: prometheus
        image: datfan06/bookstore-prometheus:latest
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-prometheus
  namespace: bookstore
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30010
  selector:
    app: bookstore-prometheus 