apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore-app
  namespace: argocd
spec:
  project: default

  source:
    # THAY ĐỔI CHO PHÙ HỢP VỚI REPO CỦA BẠN
    repoURL: 'https://github.com/DatPhan06/BookStoreApp-Microservice-App.git'
    path: 'k8s' # Đường dẫn đến thư mục chứa các manifest YAML
    targetRevision: master # Hoặc tên branch cụ thể, ví dụ 'master' hoặc 'main'

  destination:
    server: 'https://kubernetes.default.svc' # Cụm Kubernetes hiện tại
    namespace: 'bookstore' # Namespace để triển khai các service của BookStoreApp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true