name: BookStoreApp CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          
      - name: Build and Test with Maven
        run: mvn clean install 

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'bookstore-frontend-react-app/yarn.lock'
          
      - name: Install dependencies and build
        working-directory: ./bookstore-frontend-react-app
        run: |
          yarn install
          yarn build
          
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: bookstore-frontend-react-app/build/

  build-push-docker:
    name: Build & Push Docker Images
    needs: [build-test-backend] # Chỗ này hơi phân vân không biết có cho thêm frontend không
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker images
        run: |
          chmod +x build_and_push.sh
          ./build_and_push.sh ${{ secrets.DOCKER_USERNAME }}

  deploy-kubernetes:
    name: Deploy to Kubernetes
    needs: [build-push-docker]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Set Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace bookstore --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/ -n bookstore
          
      - name: Verify deployment
        run: |
          kubectl get pods -n bookstore
          kubectl get services -n bookstore
          kubectl rollout status deployment -n bookstore --timeout=300s